### ISSUE TITLE
The Wizard cannot create rules from MSIs

### ISSUE THREAD

**Issue by jgeurten** [MicrosoftDocs/WDAC-Toolkit#180]
The PS cmd invocation in Helper.cs line 1940 throws an external error: 

   at Microsoft.SecureBoot.UserConfig.WinTrust.GetAuthenticodeSha256Hash(String filename, Void* hFile, Byte[] sha256Authenticode)
   at Microsoft.SecureBoot.UserConfig.WinTrust.GetSIPSha256Hash(String fileName)
   at Microsoft.SecureBoot.UserConfig.DriverFile..ctor(String driverFilePath, Boolean userMode, Boolean isPE)
   at Microsoft.SecureBoot.UserConfig.NewCIPolicyRule.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()

**Comment by jgeurten** [comment]
Appears to be fixed in version 2.5.0.1
