### ISSUE TITLE
Bug in Get-SystemDriver -Audit PowerShell cmdlet

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/WDAC-Toolkit#302]
This is a bug in `Get-SystemDriver` [cmdlet](https://learn.microsoft.com/en-us/powershell/module/configci/get-systemdriver) when using `-Audit` parameter.

Reproducible on latest stable build of Windows 11, in Windows PowerShell and PowerShell core 7.3.6

When I use the following command:

```powershell
Get-SystemDriver -Audit
```

I get this error:

```powershell
Get-SystemDriver : An item with the same key has already been added.
At line:1 char:1
+ Get-SystemDriver -Audit
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-SystemDriver], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.SecureBoot.UserConfig.GetSystemDriver



SerializedRemoteException      : System.ArgumentException: An item with the same key has already been added.
                                    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
                                    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
                                    at Microsoft.SecureBoot.UserConfig.VersionInfo.BuildPFNDictionary()
                                    at Microsoft.SecureBoot.UserConfig.VersionInfo..ctor(String filePath, String friendlyName)
                                    at Microsoft.SecureBoot.UserConfig.DriverFile.Init(String driverFilePath)
                                    at Microsoft.SecureBoot.UserConfig.DriverFile..ctor(String driverFilePath, Boolean userMode, Boolean isPE)
                                    at Microsoft.SecureBoot.UserConfig.Helper.ReadAuditEventLogs(List`1& secureSettingList)
                                    at Microsoft.SecureBoot.UserConfig.Helper.GetDrivers(Boolean audit, List`1& secureSettingList)
                                    at Microsoft.SecureBoot.UserConfig.GetSystemDriver.ProcessRecord()
                                    at System.Management.Automation.CommandProcessor.ProcessRecord()
SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
ErrorRecord                    : An item with the same key has already been added.
WasThrownFromThrowStatement    : False
TargetSite                     : 
Message                        : An item with the same key has already been added.
Data                           : {}
InnerException                 : 
HelpLink                       : 
Source                         : 
HResult                        : -2146233087
StackTrace                     : 
```

<br>

If I clear the Code Integrity/Operational logs then this error won't occur. It must have something to do with the event logs, so I uploaded my logs to this issue in a zip, there are only 6 logs.

[Code Integrity Operational.zip](https://github.com/MicrosoftDocs/WDAC-Toolkit/files/12809356/Code.Integrity.Operational.zip)

<br>

P.S If I use the command `Get-SystemDriver -Audit` for the first time after launching PowerShell then I encounter the error, but If I then press `CTRL + C` to cancel the operation and use the command again, there won't be any errors. This is very inconvenient of course and prevents me from automating the process in PowerShell modules and/or scripts.

<br>

This is of course not related to WDAC Wizard but I really hope creating this issue will be helpful and will get this fixed.

Thanks

<br>

**Comment by jgeurten** [comment]
Thanks for reporting this issue. I have created a bug in the Windows repository

**Comment by HotCakeX** [comment]
@jgeurten Thank you very much!

**Comment by HotCakeX** [comment]
> Thanks for reporting this issue. I have created a bug in the Windows repository

Hi, i'm just wondering if there's been any updates on this bug in ConfigCI module.
