### ISSUE TITLE
Supplemental Policy - Build failure

### ISSUE THREAD

**Issue by silversurfers25** [MicrosoftDocs/WDAC-Toolkit#321]
Hi Team,
We are trying to build supplemental Policies and are receiving log errors.
We have tested this across multiple Base Policies, Locations on the PC, reinstalled WDAC & multiple machines etc.

This is the full log file with the errors in Bold/Italic : 
2023-10-26T10-32-56 [INFO]: WDAC Policy Wizard Version # 2.4.0.0
2023-10-26T10-32-56 [INFO]: Session ID: 133331184381177299
2023-10-26T10-33-01 [INFO]: **********************************************************************
2023-10-26T10-33-01 [INFO]: Workflow -- New Policy Selected
2023-10-26T10-33-01 [INFO]: **********************************************************************
2023-10-26T10-33-01 [INFO]: ==== Policy Type Page Initialized ====
2023-10-26T10-33-01 [INFO]: Setting WDAC Policy Format to MultiPolicy
2023-10-26T10-33-12 [INFO]: IsPolicyExtendable -- Policy Type: BasePolicy
**_2023-10-26T10-33-12 [INFO]: IsPolicyExtendable -- returns error code 0 (allows supplemental)_**
2023-10-26T10-33-13 [INFO]: ==== Configuration Template Page Initialized ====
2023-10-26T10-33-13 [INFO]: --- Reading Set Rules from C:\temp\TESTSUP.xml ---
2023-10-26T10-33-13 [INFO]: ==== Signing Rules Page Initialized ====
2023-10-26T10-33-13 [INFO]: --- Reading Set Signing Rules Beginning ---
2023-10-26T10-33-13 [INFO]: Reading file rules from path: C:\Program Files\WindowsApps\Microsoft.WDAC.WDACWizard_2.4.0.0_x64__8wekyb3d8bbwe\Empty_Supplemental.xml
2023-10-26T10-33-15 [INFO]: ==== Custom Signing Rules Panel Initialized ====
2023-10-26T10-33-15 [INFO]: Rule Permission set to Allow
2023-10-26T10-33-15 [INFO]: --- Create Custom Rules Selected ---
2023-10-26T10-33-19 [INFO]: Custom File Rule Level Set to Publisher
2023-10-26T10-33-36 [INFO]: --- New Custom Rule Added ---
2023-10-26T10-33-36 [INFO]: CUSTOM RULE Created: Allow - Publisher - CA: CN=DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1, O="DigiCert, Inc.", C=US & CN: CN="Samsung Electronics Co., Ltd.", O="Samsung Electronics Co., Ltd.", L=Suwon-si, S=Gyeonggi-do, C=KR & Filename: SamsungDeX.exe & Min Version: 2.4.1.18 -  
2023-10-26T10-33-39 [INFO]: **********************************************************************
2023-10-26T10-33-39 [INFO]: Workflow -- Building Policy Underway
2023-10-26T10-33-39 [INFO]: **********************************************************************
2023-10-26T10-33-39 [INFO]: --- Merge Custom Rules Policy ---
2023-10-26T10-33-39 [INFO]: --- Merge Templates Policy ---
**_2023-10-26T10-33-39 [ERROR]: MergeTemplatesPolicy() encountered the following error: Unable to locate any policies to merge_**
2023-10-26T10-33-39 [INFO]: Running the following Merge Commands: 
2023-10-26T10-33-39 [INFO]: Merge-CIPolicy -PolicyPaths -OutputFilePath "C:\temp\TESTSUP1.xml"
**_2023-10-26T10-33-39 [ERROR]: Exception encountered in MergeTemplatesPolicy(): System.Management.Automation.ParameterBindingException: Missing an argument for parameter 'PolicyPaths'. Specify a parameter of type 'System.String[]' and try again.
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at WDAC_Wizard.MainWindow.MergeTemplatesPolicy(String customRulesMergePath, BackgroundWorker worker)_**
2023-10-26T10-33-39 [INFO]: --- Create Policy Rule Options --- 
2023-10-26T10-33-39 [INFO]: -- Set Additional Parameters --
2023-10-26T10-33-39 [INFO]: -- Converting to Binary --
**_2023-10-26T10-33-39 [ERROR]: Exception encountered in ConvertPolicyToBinary(): System.Management.Automation.PSInvalidOperationException: The pipeline does not contain a command.
   at System.Management.Automation.Runspaces.PipelineBase.CoreInvoke(IEnumerable input, Boolean syncCall)
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at WDAC_Wizard.MainWindow.ConvertPolicyToBinary()_**
2023-10-26T10-33-39 [INFO]: **********************************************************************
2023-10-26T10-33-39 [INFO]: Workflow -- DONE
2023-10-26T10-33-39 [INFO]: **********************************************************************

**Comment by silversurfers25** [comment]
Just as an FYI - we have attempted this from 3 machines in the office, local accounts as well with Admin rights and the error can be replicated everytime

**Comment by jgeurten** [comment]
I cannot reproduce this for some reason even with the exact same file: 

![image](https://github.com/MicrosoftDocs/WDAC-Toolkit/assets/23045608/c08700d6-f52e-4362-b0fa-eb936b99ed03)

**Comment by jgeurten** [comment]
@silversurfers25 can you perhaps record your screen so I can follow your exact steps?
